---
title: "q4"
output: html_document
date: "2024-11-02"
---

```{r}
library(tidyverse)
library(readxl)

nsw_rct <- read.csv("data/nsw_RCT.csv", sep = ",") %>% 
  as_tibble()
nsw_rct
```

# 4.a
```{r}
nsw_rct %>% 
  group_by(treat) %>% 
  summarise(mean_income_after = mean(income.after))
```

```{r}
nsw_rct %>% 
  group_by(treat) %>% 
  summarise(mean_income_after = mean(income.after)) %>% 
  summarize(att = mean_income_after[treat == 1] - mean_income_after[treat == 0])
```

```{r}
nsw_rct %>% 
  group_by(treat) %>% 
  summarise(mean_income_after = mean(income.after)) %>% 
  summarize(att = mean_income_after[treat == 1] - mean_income_after[treat == 0])
```


```{r}
print(t.test(income.after ~ treat, data = nsw_rct))
```

# 4.b
```{r}
nsw_rct_dist_plot <- nsw_rct %>% 
  mutate(treat = ifelse(treat == 0, "Control", "Treatment")) %>% 
  ggplot() +
  geom_density(aes(x = income.after / 1000, group = treat, color = treat, fill = treat), alpha = 0., size = 1.2) +
  labs(
    title = "Distribution of Income After Training for\nControl and Treatment Groups (Thousands)",
    x = "",
    y = ""
  ) +
  theme_minimal() +
  theme(legend.position = 'bottom') +
  scale_color_manual(name = "Group", values = c("red", "blue")) +
  scale_fill_manual(name = "Group", values = c("red", "blue"))
ggsave("distribution_of_income_after_training_for_treatment_and_control.png")
```

```{r}
nsw_rct %>% 
  mutate(income_group = case_when(
    income.after <= quantile(.$income.after, 0.1) ~ "1D",
    income.after <= quantile(.$income.after, 0.2) ~ "2D",
    income.after <= quantile(.$income.after, 0.3) ~ "3D",
    income.after <= quantile(.$income.after, 0.4) ~ "4D",
    income.after <= quantile(.$income.after, 0.5) ~ "5D",
    income.after <= quantile(.$income.after, 0.6) ~ "6D",
    income.after <= quantile(.$income.after, 0.7) ~ "7D",
    income.after <= quantile(.$income.after, 0.8) ~ "8D",
    income.after <= quantile(.$income.after, 0.9) ~ "9D",
    TRUE ~ "10D"
  )) %>% 
  arrange(income.after) %>% 
  mutate(income_group = factor(income_group, levels = unique(.$income_group))) %>% 
  group_by(income_group, treat) %>% 
  summarise(count = n()) %>% 
  spread(treat, -income_group) %>% 
  purrr::set_names(c("income_group", "control", "treatment"))
```

# 4.c
```{r}
n1 <- sum(nsw_rct$treat == 1)
n0 <- sum(nsw_rct$treat == 0)
n <- n1 + n0

mean_treated <- mean(nsw_rct$income.after[nsw_rct$treat == 1])
mean_control <- mean(nsw_rct$income.after[nsw_rct$treat == 0])

var_treated <- var(nsw_rct$income.after[nsw_rct$treat == 1])
var_control <- var(nsw_rct$income.after[nsw_rct$treat == 0])

variance_att <- var_treated / n1 + var_control / n0

se_att <- sqrt(variance_att)

z_alpha <- qnorm(0.95)

lower_bound <- (mean_treated - mean_control) - z_alpha * se_att
upper_bound <- (mean_treated - mean_control) + z_alpha * se_att

cat("Estimated ATT:", mean_treated - mean_control, "\n")
cat("Standard Error:", se_att, "\n")
cat("90% Confidence Interval: [", lower_bound, ",", upper_bound, "]\n")
```


```{r}
binary_covariate_list <- c("black", "hispanic", "married", "hsdegree")

all_binary_groups_att <- data.frame()

for (binary_covariate in binary_covariate_list) {
  group_att <- nsw_rct %>%
    rename(covariate := !!binary_covariate) %>% 
    group_by(treat, covariate) %>% 
    summarise(
      avg = mean(income.after)
    ) %>% 
    ungroup() %>% 
    spread(treat, avg) %>% 
    purrr::set_names("covariate", "control_mean", "treatment_mean") %>% 
    mutate(att_group = treatment_mean - control_mean) %>% 
    left_join(
      nsw_rct %>% 
        rename(covariate := !!binary_covariate) %>% 
        group_by(covariate) %>% 
        summarise(
          n = n()
        ) %>% 
        ungroup()
    ) %>% 
    mutate(wealth = n * att_group) %>% 
    mutate(covariate_name = binary_covariate)
  all_binary_groups_att <- all_binary_groups_att %>% rbind(group_att)
}

all_binary_groups_att <- all_binary_groups_att %>% 
  mutate(covariate_threshold = paste(covariate_name, "=", covariate))

all_binary_groups_att %>% arrange(desc(wealth))
```

```{r}
discrete_covariate_list <- c("age", "education", "income.before1", "income.before2")

all_discrete_groups_att <- data.frame()

for (discrete_covariate in discrete_covariate_list) {
  
  covariate_unique_values <- nsw_rct %>%
    rename(covariate := !!discrete_covariate) %>%
    arrange(covariate) %>% 
    .$covariate %>% unique()
  
  for (covariate_value in covariate_unique_values) {
    
    new_covariate_name <- paste(discrete_covariate, "<=", covariate_value)
    
    group_att <- nsw_rct %>%
      rename(covariate := !!discrete_covariate) %>% 
      mutate(covariate = ifelse(covariate <= covariate_value, 1, 0)) %>% 
      group_by(treat, covariate) %>% 
      summarise(
        avg = mean(income.after)
      ) %>% 
      ungroup() %>% 
      spread(treat, avg) %>% 
      purrr::set_names("covariate", "control_mean", "treatment_mean") %>% 
      mutate(att_group = treatment_mean - control_mean) %>% 
      left_join(
        nsw_rct %>% 
          rename(covariate := !!discrete_covariate) %>% 
          mutate(covariate = ifelse(covariate <= covariate_value, 1, 0)) %>% 
          group_by(covariate) %>% 
          summarise(
            n = n()
          ) %>% 
          ungroup()
      ) %>% 
      mutate(wealth = n * att_group) %>% 
      mutate(covariate_name = discrete_covariate) %>% 
      mutate(covariate_threshold = ifelse(covariate == 0, sub("<=", ">", new_covariate_name), new_covariate_name))
    all_discrete_groups_att <- all_discrete_groups_att %>% rbind(group_att)
  }
}

all_discrete_groups_att %>% arrange(desc(wealth)) %>% select(-covariate)
```
```{r}
all_groups_att <- all_discrete_groups_att %>% rbind(all_binary_groups_att)

all_groups_att %>% 
   arrange(desc(wealth)) %>% select(-covariate)
```

```{r}

all_groups_att %>% 
  arrange(desc(wealth)) %>% 
  distinct(covariate_name, .keep_all = TRUE) %>% 
  head(10) %>% 
  select(covariate_threshold, wealth) %>% 
  mutate(covariate_threshold = factor(covariate_threshold, levels = covariate_threshold %>% rev())) %>% 
  ggplot(aes(covariate_threshold, wealth / 1000)) +
  geom_bar(stat = "identity", fill = 'darkblue') +
  coord_flip() +
  theme_minimal() +
  labs(
    title = "Wealthfare Increase by Policy Targeting",
    y = 'ATT for Group x Nº Obs Group (Thousands)',
    x = 'Policy Targeting'
  )
ggsave('wealth_increase_by_policy_targeting.png', width = 7, height = 5)

```


```{r}
lm(
  income.after ~ .,
  data = nsw_rct %>% 
    mutate(treat = factor(treat, levels = c(0, 1)))
) %>% summary()
```


# 4.f
```{r}
nws_rct_filtered_target_rule <- nsw_rct %>% 
  filter(income.before1 <= 2143.413) %>% 
  mutate(reverse_treat = 1 - treat)

t.test(income.after ~ treat, data = nws_rct_filtered_target_rule, alternative = "less", var.equal = FALSE)
```

```{r}
t.test(income.after ~ reverse_treat, data = nws_rct_filtered_target_rule, alternative = "greater", var.equal = FALSE)
```
```{r}
lm(
  income.after ~ target * treat + treat + target,
  data = nsw_rct %>% 
    mutate(target = ifelse(income.before1 <= 2143.413, 1, 0))
) %>% summary()
```
# 4.g
```{r}
covariate_levels <- c(
  "avg_income_after",
  "std_income_after",
  "pct_treated",
  "pct_black",
  "pct_married",
  "pct_hispanic",
  "pct_hsdegree",
  "avg_education",
  "std_education",
  "avg_age",
  "std_age",
  "avg_income_before1",
  "std_income_before1",
  "avg_income_before2",
  "std_income_before2",
  "n"
)

nsw_rct %>% 
  mutate(target = ifelse(income.before1 <= 2143.413, 1, 0)) %>% 
  group_by(target) %>% 
  summarise(
    avg_income_after = mean(income.after),
    std_income_after = sd(income.after),
    pct_black = mean(black),
    pct_married = mean(married),
    pct_hispanic = mean(hispanic),
    pct_hsdegree = mean(hsdegree),
    pct_treated = mean(treat),
    avg_education = mean(education),
    std_education = sd(education),
    avg_age = mean(age, na.rm = TRUE),
    std_age = sd(age, na.rm = TRUE),
    n = n(),
    avg_income_before2 = mean(income.before2),
    std_income_before2 = sd(income.before2),
    avg_income_before1 = mean(income.before1),
    std_income_before1 = sd(income.before1),
  ) %>% 
  gather(id, value, -target) %>% 
  spread(target, value) %>% 
  mutate(id = factor(id, levels = covariate_levels)) %>% 
  arrange(id)
  
```


# 4.d old
```{r}
nsw_rct_wealthfare <- nsw_rct %>% 
  mutate(y = income.after - income.before1) %>% 
  select(-income.before1, -income.before2, -income.after) %>% 
  ungroup() %>% 
  mutate(
    age_treat = treat * (age - mean(age)),
    education_treat = treat * (education - mean(education)),
    black_treat = black * treat,
    hispanic_treat = hispanic * treat,
    married_treat = married * treat,
    hsdegree_treat = hsdegree * treat
  )
  

nsw_rct_wealthfare_ols_model <- lm(y ~ ., nsw_rct_diff)

nsw_rct_wealthfare_ols_model %>% summary()
```

```{r}
potential_nsw_rct_wealthfare <- nsw_rct_wealthfare %>% 
  mutate(
    potential_y1 = predict(
      nsw_rct_wealthfare_ols_model,
      nsw_rct_wealthfare %>% select(-y) %>%
        mutate(treat = 1) %>% 
        mutate(
          age_treat = treat * (age - mean(age)), # Should I demean age and education?
          education_treat = treat * (education - mean(education)),
          black_treat = black * treat,
          hispanic_treat = hispanic * treat,
          married_treat = married * treat,
          hsdegree_treat = hsdegree * treat
        )
    ),
    potential_y0 = predict(
      nsw_rct_wealthfare_ols_model,
      nsw_rct_wealthfare %>% select(-y) %>% 
        mutate(treat = 0) %>% 
        mutate(
          age_treat = treat * (age - mean(age)),
          education_treat = treat * (education - mean(education)),
          black_treat = black * treat,
          hispanic_treat = hispanic * treat,
          married_treat = married * treat,
          hsdegree_treat = hsdegree * treat
        )
    ),
    # y1_minus_y0 = potential_y1 - potential_y0,
    y1_minus_y0 = ifelse(treat == 1, y, potential_y1) - ifelse(treat == 0, y, potential_y0)
  ) %>% 
  select(y, potential_y1, potential_y0, y1_minus_y0, everything(.))

potential_nsw_rct_wealthfare
```
```{r}
potential_nsw_rct_wealthfare %>% 
  group_by(black) %>% 
  summarise(y1_minus_y0 = sum(y1_minus_y0))
```
```{r}
potential_nsw_rct_wealthfare %>% 
  group_by(hispanic) %>% 
  summarise(y1_minus_y0 = sum(y1_minus_y0))
```

```{r}
potential_nsw_rct_wealthfare %>% 
  group_by(married) %>% 
  summarise(y1_minus_y0 = sum(y1_minus_y0))
```

```{r}
potential_nsw_rct_wealthfare %>% 
  group_by(hsdegree_treat) %>% 
  summarise(y1_minus_y0 = sum(y1_minus_y0))
```

```{r}
potential_nsw_rct_wealthfare %>% 
  group_by(age) %>% 
  summarise(y1_minus_y0 = sum(y1_minus_y0))
```

```{r}
potential_nsw_rct_wealthfare %>% 
  group_by(education) %>% 
  summarise(y1_minus_y0 = sum(y1_minus_y0))
```
