---
title: "q1g"
output: html_document
date: "2024-11-14"
---

```{r}
library(MASS)
library(stats)
library(tidyverse)
library(glmnet)
library(rsample)
```

```{r}
banerji_raw <- read_csv("Banerji-Berry-Shotland_2017_AEJ.csv")
banerji_raw
```

```{r}
discrete_features <- banerji_raw %>% 
  select(-treatment) %>% 
  gather(id, value) %>% 
  group_by(id, value) %>% 
  summarise(count = n(), .groups = 'keep') %>% 
  ungroup() %>% 
  group_by(id) %>% 
  summarise(n_diff_values = n(), .groups = 'keep') %>% 
  ungroup() %>% 
  arrange(n_diff_values) %>% 
  filter(n_diff_values <= 2) %>% 
  .$id
```

# 3.A
```{r}
banerji_data <- banerji_raw %>% 
  arrange(treatment) %>% 
  mutate(treatment = factor(treatment, levels = unique(.$treatment))) %>% 
  mutate(
    t2 = ifelse(treatment == 2, 1, 0),
    t3 = ifelse(treatment == 3, 1, 0),
    t4 = ifelse(treatment == 4, 1, 0),
  ) %>% 
  select(-treatment)

features <- banerji_data %>% colnames()
features <- features[!features %in% c("treatment", "caser_total_norm", "t2", "t3", "t4")]
continous_features <- features[(!features %in% discrete_features) & (!features %in% c("t2", "t3", "t4"))]

banerji_demeaned_data <- banerji_data %>% 
  mutate(across(features, ~ (. - mean(.)), .names = "{.col}"))

banerji_interaction_with_treatment_data <- banerji_demeaned_data %>% 
  mutate(across(features, ~ . * t2, .names = "{.col}:t2")) %>% 
  mutate(across(features, ~ . * t3, .names = "{.col}:t3")) %>% 
  mutate(across(features, ~ . * t4, .names = "{.col}:t4"))

banerji_interaction_with_discrete_features_data <- banerji_demeaned_data %>% 
  mutate(across(discrete_features, ~ . * age, .names = "{.col}:age")) %>% 
  mutate(across(discrete_features, ~ . * bl_caser_total_norm, .names = "{.col}:bl_caser_total_norm")) %>% 
  mutate(across(discrete_features, ~ . * number_of_kids, .names = "{.col}:number_of_kids"))
```

```{r}
lm(
  caser_total_norm ~ .,
  data = banerji_data %>% 
    select(caser_total_norm, t2, t3, t4)
) %>% 
  summary()
```

```{r}
lm(
  caser_total_norm ~ ., data = banerji_data
) %>% 
  summary()
```

```{r}
lm(
  caser_total_norm ~ .,
  data = banerji_demeaned_data
) %>%
  summary()
```

```{r}
lm(
  caser_total_norm ~ ., data = banerji_interaction_with_treatment_data
) %>% 
  summary()
```
```{r}
lm(
  caser_total_norm ~ ., data = banerji_interaction_with_discrete_features_data
) %>% 
  summary()
```

# 3.B
# LASSO on Model without Interaction
```{r}
selected_data <- as_tibble(banerji_data)

treatment_features <- selected_data %>% 
  select(starts_with("t"))

n_treatment_features <- length(treatment_features %>% colnames())

other_features <- selected_data %>% 
  select(-starts_with("t")) %>% 
  select(-caser_total_norm) %>% 
  mutate_all(~ (. - mean(.)) / sd(.))

n_other_features <- length(other_features %>% colnames())

all_features <- cbind(other_features, treatment_features) %>% 
  as.matrix()

penalty_factors <- c(rep(1, n_other_features), rep(0, n_treatment_features))

cv_model <- cv.glmnet(
  all_features, selected_data$caser_total_norm,
  alpha = 1,
  penalty.factor = penalty_factors
)

best_lambda <- cv_model$lambda.min
coefficients <- coef(cv_model, s = "lambda.min")
print(paste('Best lambda:', best_lambda))
print(coefficients)

non_zero_features <- coef(cv_model, s = "lambda.min")[-1] != 0

lm(
  caser_total_norm ~ .,
  banerji_interaction_with_discrete_features_data %>% 
    select(all_features %>% colnames()) %>% 
    .[, non_zero_features] %>% 
    cbind(
      banerji_interaction_with_discrete_features_data %>% 
        select(caser_total_norm)
    )
) %>% 
  summary()
```

# LASSO on Model with Interaction between Discrete and Continuous Covariates
```{r}
selected_data <- as_tibble(banerji_interaction_with_discrete_features_data)

treatment_features <- selected_data %>% 
  select(starts_with("t"))

n_treatment_features <- length(treatment_features %>% colnames())

other_features <- selected_data %>% 
  select(-starts_with("t")) %>% 
  select(-caser_total_norm) %>% 
  mutate_all(~ (. - mean(.)) / sd(.))

n_other_features <- length(other_features %>% colnames())

all_features <- cbind(other_features, treatment_features) %>% 
  as.matrix()

penalty_factors <- c(rep(1, n_other_features), rep(0, n_treatment_features))

cv_model <- cv.glmnet(
  all_features, selected_data$caser_total_norm,
  alpha = 1,
  penalty.factor = penalty_factors
)

best_lambda <- cv_model$lambda.min
coefficients <- coef(cv_model, s = "lambda.min")
print(paste('Best lambda:', best_lambda))
print(coefficients)

non_zero_features <- coef(cv_model, s = "lambda.min")[-1] != 0

lm(
  caser_total_norm ~ .,
  selected_data %>% 
    select(all_features %>% colnames()) %>% 
    .[, non_zero_features] %>% 
    cbind(
      selected_data %>% 
        select(caser_total_norm)
    )
) %>% 
  summary()
```

# LASSO on Model with Interaction between Features and Treatment
```{r}
selected_data <- as_tibble(banerji_interaction_with_treatment_data)

treatment_features <- selected_data %>% 
  select(starts_with("t"))

n_treatment_features <- length(treatment_features %>% colnames())

other_features <- selected_data %>% 
  select(-starts_with("t")) %>% 
  select(-caser_total_norm) %>% 
  mutate_all(~ (. - mean(.)) / sd(.))

n_other_features <- length(other_features %>% colnames())

all_features <- cbind(other_features, treatment_features) %>% 
  as.matrix()

penalty_factors <- c(rep(1, n_other_features), rep(0, n_treatment_features))

cv_model <- cv.glmnet(
  all_features, selected_data$caser_total_norm,
  alpha = 1,
  penalty.factor = penalty_factors
)

best_lambda <- cv_model$lambda.min
coefficients <- coef(cv_model, s = "lambda.min")
print(paste('Best lambda:', best_lambda))
print(coefficients)

non_zero_features <- coef(cv_model, s = "lambda.min")[-1] != 0

lm(
  caser_total_norm ~ .,
  selected_data %>% 
    select(all_features %>% colnames()) %>% 
    .[, non_zero_features] %>% 
    cbind(
      selected_data %>% 
        select(caser_total_norm)
    )
) %>% 
  summary()
```

# 3.C
```{r}
selected_discrete_variable <- 'mother_educ'

lm(
  caser_total_norm ~ .,
  banerji_data %>% 
    select(t2, t3, t4, selected_discrete_variable, caser_total_norm) %>% 
    purrr::set_names("t2", "t3", "t4", "selected_discrete_variable", "caser_total_norm") %>% 
    mutate(across(
      c("t2", "t3", "t4"), ~ . * selected_discrete_variable, 
      .names = "{.col}:{selected_discrete_variable}"
    )) %>% 
    rename_with(~ gsub("selected_discrete_variable", selected_discrete_variable, .))
) %>%
  summary()

lm(
  caser_total_norm ~ .,
  banerji_data %>% 
    select(t2, t3, t4, selected_discrete_variable, caser_total_norm) %>% 
    purrr::set_names("t2", "t3", "t4", "selected_discrete_variable", "caser_total_norm") %>% 
    filter(selected_discrete_variable == 1) %>% 
    select(-selected_discrete_variable)
) %>%
  summary()

lm(
  caser_total_norm ~ .,
  banerji_data %>% 
    select(t2, t3, t4, selected_discrete_variable, caser_total_norm) %>% 
    purrr::set_names("t2", "t3", "t4", "selected_discrete_variable", "caser_total_norm") %>% 
    filter(selected_discrete_variable == 0) %>% 
    select(-selected_discrete_variable)
) %>%
  summary()
```
# 3.D
```{r}
discrete_features <- discrete_features[discrete_features != selected_discrete_variable]

banerji_interaction_interactions_and_polinomials_data <- banerji_data %>% 
  mutate(across(discrete_features, ~ . * age, .names = "{.col}:age")) %>% 
  mutate(across(discrete_features, ~ . * bl_caser_total_norm, .names = "{.col}:bl_caser_total_norm")) %>% 
  mutate(across(discrete_features, ~ . * number_of_kids, .names = "{.col}:number_of_kids")) %>% 
  mutate(
    "age:bl_caser_total_norm" = bl_caser_total_norm * age,
    "age:number_of_kids" = age * number_of_kids,
    "bl_caser_total_norm:number_of_kids" = bl_caser_total_norm * number_of_kids,
  ) %>% 
  mutate(across(continous_features, ~ .^2, .names = "{.col}^2")) %>% 
  mutate(across(continous_features, ~ .^3, .names = "{.col}^3"))

selected_data <- as_tibble(banerji_interaction_interactions_and_polinomials_data)

treatment_features <- banerji_interaction_interactions_and_polinomials_data %>% 
  select(starts_with("t"), selected_discrete_variable) %>% 
  purrr::set_names("t2", "t3", "t4", "selected_discrete_variable") %>% 
  mutate(across(
    c("t2", "t3", "t4"), ~ . * selected_discrete_variable, 
    .names = "{.col}:{selected_discrete_variable}"
  )) %>% 
  rename_with(~ gsub("selected_discrete_variable", selected_discrete_variable, .))

n_treatment_features <- length(treatment_features %>% colnames())

other_features <- selected_data %>% 
  select(-starts_with("t")) %>% 
  select(-selected_discrete_variable) %>% 
  select(-caser_total_norm) %>% 
  mutate_all(~ (. - mean(.)) / sd(.))

n_other_features <- length(other_features %>% colnames())

all_features <- cbind(other_features, treatment_features) %>% 
  as.matrix()

penalty_factors <- c(rep(1, n_other_features), rep(0, n_treatment_features))

cv_model <- cv.glmnet(
  all_features, selected_data$caser_total_norm,
  alpha = 1,
  penalty.factor = penalty_factors
)

best_lambda <- cv_model$lambda.min
coefficients <- coef(cv_model, s = "lambda.min")
print(paste('Best lambda:', best_lambda))
print(coefficients)

non_zero_features <- coef(cv_model, s = "lambda.min")[-1] != 0

lm(
  caser_total_norm ~ .,
  as_tibble(all_features) %>% 
    .[, non_zero_features] %>% 
    cbind(
      selected_data %>% 
        select(caser_total_norm)
    )
) %>% 
  summary()
```

# 3.E
```{r}
create_interactions <- function(data, interaction_order) {
  feature_names <- colnames(data)
  
  combinations <- combn(feature_names, interaction_order, simplify = FALSE)
  
  interaction_data <- lapply(combinations, function(comb) {
    interaction_term <- apply(data[comb], 1, prod)
    interaction_name <- paste(comb, collapse = ":")
    data.frame(interaction_term) |> setNames(interaction_name)
  })
  
  do.call(cbind, interaction_data)
}

selected_data <- banerji_data %>%
  select(-caser_total_norm) %>% 
  select(-selected_discrete_variable, -t2, -t3, -t4)

treatment_features <- banerji_data %>% 
  select(starts_with("t"), selected_discrete_variable) %>% 
  purrr::set_names("t2", "t3", "t4", "selected_discrete_variable") %>% 
  mutate(across(
    c("t2", "t3", "t4"), ~ . * selected_discrete_variable, 
    .names = "{.col}:{selected_discrete_variable}"
  )) %>% 
  rename_with(~ gsub("selected_discrete_variable", selected_discrete_variable, .))

pairwise_interaction <- create_interactions(selected_data, 2)
threewise_interaction <- create_interactions(selected_data, 3)

banerji_data_pairwise_threewise_interactions <- cbind(
  selected_data,
  pairwise_interaction,
  threewise_interaction
) %>% 
  mutate_all(~ (. - mean(.)) / sd(.)) %>% 
  cbind(
    banerji_data %>% select(caser_total_norm),
    treatment_features
  )

set.seed(42)

n_obs <- banerji_data_pairwise_threewise_interactions %>% nrow()

sample_a_indices <- sample(1:n_obs, size = .5 * n_obs)
sample_b_indices <- setdiff(1:n_obs, sample_a_indices)

sample_a <- banerji_data_pairwise_threewise_interactions[sample_a_indices, ]
sample_b <- banerji_data_pairwise_threewise_interactions[sample_b_indices, ]

penalty_factors <- c(
  rep(1, ncol(banerji_data_pairwise_threewise_interactions) - ncol(treatment_features) - 1),
  rep(0, treatment_features %>% ncol())
)

cv_model <- cv.glmnet(
  as.matrix(sample_a %>% select(-caser_total_norm)), sample_a$caser_total_norm,
  alpha = 1,
  penalty.factor = penalty_factors
)

best_lambda <- cv_model$lambda.min
coefficients <- coef(cv_model, s = "lambda.min")
print(paste('Best lambda:', best_lambda))
print(coefficients)

non_zero_features <- coef(cv_model, s = "lambda.min")[-1] != 0

mean(non_zero_features)

lm(
  caser_total_norm ~ .,
  sample_b %>% 
    .[, non_zero_features] %>% 
    cbind(
      sample_b %>% 
        select(caser_total_norm)
    )
) %>% 
  summary()

lm(
  caser_total_norm ~ .,
  sample_a %>% 
    .[, non_zero_features] %>% 
    cbind(
      sample_a %>% 
        select(caser_total_norm)
    )
) %>% 
  summary()
```



